version: '3.3'

services:

        dev-environment:
                build: .
                container_name: dev-environment
                ports:
                        - 8900:8900
                environment:
                        JUPYTER_ENABLE_LAB: "yes"
                        JUPYTER_TOKEN: "token"